### ISSUE TITLE
Implementer grafsøgning i MCTS

### ISSUE THREAD

**Issue by asgerius** [asgerius/rl-rubiks#31]

**Comment by asgerius** [comment]
BFS ned gennem træet. Brug node.neighs og ikke self.states til at søge gennem grafen

**Comment by sorenmulli** [comment]
Flaky bug in `pytest tets/test_searcher.py` : 
![billede](https://user-images.githubusercontent.com/42035306/82444029-d8bf0c00-9aa2-11ea-8c20-b5e70c4ec10a.png)
